---
title: "AirBNB dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(flexdashboard)
```



```{r include = FALSE}
data("ny_noaa")

central_park_noaa = ny_noaa %>% 
  separate(col = 'date', into = c('year', 'month', 'day'), sep = '-') %>%
  filter(year %in% 2005:2010,
    id == "USW00094728") %>%
  mutate(
        snow = (snow/10),
         snwd = (snwd/10),
         tmax = (as.numeric(tmax))/10,
         tmin = (as.numeric(tmin))/10
  )

ny_noaa_sub = ny_noaa %>% 
  separate(col = 'date', into = c('year', 'month', 'day'), sep = '-') %>%
  filter(year %in% 2005:2010) %>% 
  mutate(
        snow = (snow/10),
         snwd = (snwd/10),
         tmax = (as.numeric(tmax))/10,
         tmin = (as.numeric(tmin))/10
  )


```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}

central_park_noaa %>% 
  group_by(month, year) %>% 
  summarize(avg_prcp = mean(prcp)) %>% 
  plot_ly(
    x = ~month, y = ~avg_prcp, color = ~year,
    type = "bar", colors = "viridis"
  )

```


Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
central_park_noaa %>% 
  group_by(month) %>% 
  plot_ly(
    y = ~tmin, color = ~month,
    type = "box", colors = "viridis"
  )
```

### Chart C

```{r}
central_park_noaa %>% 
  group_by(month) %>% 
  plot_ly(
    y = ~tmax, color = ~month,
    type = "box", colors = "viridis"
  )
```
### Chart D

```{r}
ny_noaa_sub %>% 
  filter(year == 2010) %>% 
  group_by(month) %>% 
  plot_ly(
    y = ~prcp, x = ~month,
    type = "scatter", mode = "markers", fill = "tozeroy",
    alpha = .5
  )



ny_noaa_sub %>%
  filter(year == 2005) %>% 
  plot_ly(
    x = ~month,
    y = ~prcp,
    split = ~month,
    type = 'violin',
    box = list(
      visible = T
    ),
    meanline = list(
      visible = T
    )
  ) 

ny_noaa_sub %>% 
  plot_ly( x = ~month, y = ~prcp, text = ~prcp, type = 'scatter', mode = 'markers',
        marker = list(size = ~prcp, opacity = 0.5))

```

